### ISSUE TITLE
Toolbar Buttons' Tint Hard to Read in Some Color Schemes

### ISSUE THREAD

**Issue by Angelk90** [dbarsamian/conscriptor#1]
Hi @dbarsamian , 

1) When using dark mode I get the following result, you don't see the buttons very well.

<img width="277" alt="Schermata 2021-09-07 alle 15 19 01" src="https://user-images.githubusercontent.com/20476002/132351800-a0758c8a-9413-4e68-a021-ed61acc25940.png">

2) When I try to compile I get the following error, I am using Xcode Version 12.5.1.
<img width="804" alt="Schermata 2021-09-07 alle 15 22 01" src="https://user-images.githubusercontent.com/20476002/132352033-de76392a-a3a9-45bf-a90a-14848c00d90d.png">

3) It would be very interesting to have a db, where you can save personal models.

For example, you create a new document and then select a template that I created some time ago.

**Comment by dbarsamian** [comment]
Firstly, thank you for the feedback. On your second point, I should note that I am using the latest Xcode 13 beta to write this project, so I recommend opening the project using that and seeing if the compile error goes away. I'll update the `README` so it's clearer.

As for the button appearances, I also am experiencing some odd behaviors with tinting in color schemes. I'll focus this issue specifically on that.

And for the final suggestion, I like the idea of some kind of template system. I think it may need to be a post-release feature, but I will definitely keep it in mind.
