### ISSUE TITLE
Add attribute details

### ISSUE THREAD

**Issue by Angelk90** [dbarsamian/conscriptor#6]
**Is your feature request related to a problem? Please describe.**

It would be useful to add the following attribute:
<details>
  <summary>
  Summary
  </summary>
  Text...
</details>

**Describe the solution you'd like**

@dbarsamian :
```
<details>
  <summary>
  Summary
  </summary>
  Text...
</details>
```

**Comment by dbarsamian** [comment]
There is a chance I will be moving to using the [CommonMark Spec](https://spec.commonmark.org/0.30/) for this project, which includes HTML blocks like `<details>` and `<summary>` among others. I'm currently testing some other solutions for using Markdown in this project, so this will likely end up supported.

**Comment by dbarsamian** [comment]
@Angelk90 This is officially supported as of commit 26bc41bd1c76b7561a129552af782158ba6e7a3b. Below is an example of how the feature looks in the app. Note that with this comes support for *all* inline HTML tags.

<img width="720" alt="image" src="https://user-images.githubusercontent.com/46636471/141638635-9453c306-2b5a-428e-baac-b3f1c123c3a6.png">
