### ISSUE TITLE
Show code icon

### ISSUE THREAD

**Issue by Angelk90** [dbarsamian/conscriptor#8]
**Describe the bug**
@dbarsamian : You do not see the icon to enter the code.

**Screenshots**

https://user-images.githubusercontent.com/20476002/141771148-2df7818c-c02e-48bf-8302-9ab04ae80236.mov

**Device (please complete the following information):**
 - OS: Big Sur 11.5

**Comment by dbarsamian** [comment]
Appears to be an issue with SF Symbols: the name has been updated for macOS Monterey+. Added in legacy name for older macOS versions.

**Comment by Angelk90** [comment]
@dbarsamian :  For the code it would not be better to use the multiline this: ```
