### ISSUE TITLE
Download readme template

### ISSUE THREAD

**Issue by Angelk90** [dbarsamian/conscriptor#9]
**Is your feature request related to a problem? Please describe.**
It would be nice to be able to insert the url link of a project for example on github and be able to automatically have that model, without having to copy and paste it or having to download it manually and then having to open it.

**Describe the solution you'd like**
@dbarsamian : Clicking on a button requests url of the project, automatically takes the readme file by default if no name is specified and takes the text in question and puts it in the new file.

**Comment by dbarsamian** [comment]
With the addition of custom templates, I am considering this issue resolved and closing. I believe at this time it's out of the scope of this project to include downloading of files from a URL, however this may or may not change in the future.
